Use makefile.proj if available
aspnet/KoreBuild pull request #158
Opened 2017-01-30 20:26 UTC by pranavkm

2017-01-30 20:42 UTC, natemcmaster commented
`makefile.proj` will break all shorthand dotnet commands since it matches the `*.*proj` pattern. This would require you to explicitly call `dotnet build Repo.sln` now and `dotnet restore Repo.sln`.

As an alternative, consider adding a msbuild project into KoreBuild that conditionally imports `makefile.targets` from the repo folder if it exists. This has the added benefit of allowing us to start moving the Sake lifecycle into an MSBuild project.

Concept:
in KoreBuild
```xml
<Project>
    <Target Name="Build" />
    <Import Project="$(RepoDir)\makefile.targets" Condition="Exists('$(RepoDir)\makefile.targets')" />
</Project>
```

in repo
```xml
<Project>
   <Target Name="AfterBuild" AfterTargets="Build" />
</Project>
```

2017-01-30 23:10 UTC, pranavkm commented
build/makefile.proj if the file in the root affects builds? Presumably that solves and moves more build related files to the build dir.

2017-01-31 01:18 UTC, natemcmaster commented
I like the idea of putting it in the build/ folder. How about build/repo.targets ?

2017-01-31 19:22 UTC, pranavkm commented
🆙 📅  with corresponding changes to https://github.com/aspnet/CoreCLR/pull/149/

2017-01-31 19:45 UTC, natemcmaster requested changes
👏 I like where this is going. A few changes suggested.

2017-01-31 19:45 UTC, natemcmaster commented on build/targets/standard-lifecycle.targets
> +<Project>
Should this be set to `DefaultTargets="Default"`?

2017-01-31 19:45 UTC, natemcmaster commented on build/targets/legacy-lifecycle.targets
> +      Command="$(SakeExecutable) -I $(KoreBuildDirectory)shade -f $(MakeFilePath) $(ShadeTarget)"
I did this exact same work a few weeks ago (bu never finished it) and ran into issues with relative vs absolute paths. Sake.exe didn't recognize absolute paths for the `-f` argument. Have you run into this issue here?

2017-01-31 19:45 UTC, natemcmaster commented on build/KoreBuild.ps1
> +dotnet msbuild $makeFileProj /p:KoreBuildDirectory="$koreBuildFolder\" /p:RepositoryRoot="$repoFolder\" $targets
$targets needs to be surrounded with double quotes so multiple targets doesn't terminate the line.

Suggested adding these parameters:
/maxcpucount /fileLogger /fileloggerparameters:LogFile=artifacts/msbuild.log /detailedsummary

Also, consider making an rsp file (artifacts/msbuild.rsp) and executing "dotnet msbuild @artifacts/msbuild.rsp" instead.

Nit: add newline at end of file.

2017-01-31 21:05 UTC, pranavkm commented on build/KoreBuild.ps1
> +dotnet msbuild $makeFileProj /p:KoreBuildDirectory="$koreBuildFolder\" /p:RepositoryRoot="$repoFolder\" $targets
I actually tried multiple targets and it works fine - primarily because the `$targets` is a variable and not code in the file with semicolons.

2017-01-31 21:05 UTC, pranavkm commented on build/targets/legacy-lifecycle.targets
> +      Command="$(SakeExecutable) -I $(KoreBuildDirectory)shade -f $(MakeFilePath) $(ShadeTarget)"
`KoreBuildDirectory` is root relative - notice I had to concat the path on Line 145 with `RepositoryRoot` to make it absolute. Btw, this brought up an interesting issue with using back slashes in our code - the things we invoke on xplat don't like back slashes (for instance `mono build\sake.exe`). Calling `Path.GetFullPath` helps, but it'd be much better to standardize on forward slashes in our targets.

2017-01-31 21:05 UTC, pranavkm commented on build/targets/standard-lifecycle.targets
> +<Project>
This gets included by `makefile.proj` which has the DefaultTarget. Would we need one here?

2017-01-31 21:34 UTC, natemcmaster commented on build/targets/standard-lifecycle.targets
> +<Project>
nope, you're right. I just didn't see that

2017-01-31 21:38 UTC, natemcmaster commented on build/targets/legacy-lifecycle.targets
> +      Command="$(SakeExecutable) -I $(KoreBuildDirectory)shade -f $(MakeFilePath) $(ShadeTarget)"
gotcha. was just checking :)

2017-01-31 21:38 UTC, natemcmaster commented on build/KoreBuild.ps1
> +dotnet msbuild $makeFileProj /p:KoreBuildDirectory="$koreBuildFolder\" /p:RepositoryRoot="$repoFolder\" $targets
glad this PowerShell quirk works in our favor.

2017-02-01 21:10 UTC, pranavkm commented
🆙 📅

2017-02-01 21:53 UTC, natemcmaster commented on build/KoreBuild.sh
> +dotnet msbuild @"$msbuildResponseFile"
On more thought. Right now this converts $@ to a list of targets. How would we go about flowing through properties? e.g. `/p:Configuration=Release`.

2017-02-01 21:56 UTC, natemcmaster approved these changes

2017-02-03 17:20 UTC, natemcmaster commented
:bell: can we get this in soon? I want to rebase #159 off of this work.

2017-02-03 18:07 UTC, pranavkm commented
Merged. Let's see how this goes.

2017-02-03 18:07 UTC, closed without merging

2017-02-03 18:13 UTC, pranavkm commented
Ok - need to tweak this so that it allows calling targets that aren't declared in KoreBuild (for instance Universe has different targets). I'll play around with this and resend.

2017-02-03 18:24 UTC, pranavkm commented
I'll send an update to this later.