Merge feature/msbuild to dev
aspnet/KoreBuild pull request #171
Opened 2017-02-14 20:54 UTC by natemcmaster

We only have two repos left on 'dev' EF and MVC. I'll pin their build.ps1 before we merge this.

This deprecates support for building project.json with KoreBuild.

2017-02-24 22:13 UTC, pranavkm requested changes

2017-02-24 22:13 UTC, pranavkm commented on build/KoreBuild.ps1
> -    InstallSharedRuntime '1.0.0' 'preview'
Do none of our tools need 1.0.0 anymore?

2017-02-24 22:13 UTC, pranavkm commented on build/KoreBuild.ps1
> +    # TODO restore installing pre-release versions of sharedfx when we upgrade to .NET Core 2.0
No TODOs or commented out code.

2017-02-24 22:13 UTC, pranavkm commented on build/KoreBuild.ps1
> +# TODO remove. dotnet nuget push now exists
Let's file a bug and remove the todo.

2017-02-24 22:13 UTC, pranavkm commented on build/KoreBuild.sh
> +    # TODO restore installing pre-release versions of sharedfx when we upgrade to .NET Core 2.0
ditto

2017-02-24 22:13 UTC, pranavkm commented on build/NuGet.config
> +</configuration>
Undo

2017-02-24 22:13 UTC, pranavkm commented on build/dotnet/dotnet-install.ps1
>  .PARAMETER Verbose
Seems unrelated to the msbuild conversion. Make this a separate commit

2017-02-24 22:13 UTC, pranavkm commented on build/targets/standard-lifecycle.targets
> +    <!-- TODO if VS Test doesn't make minimal output the default log setting, we can set that here. cref https://github.com/Microsoft/vstest/issues/301 -->
This is fixed. Remove

2017-02-24 22:13 UTC, pranavkm commented on build/targets/standard-lifecycle.targets
> +    <!-- TODO consider using GeneratePackageOnBuild or calling Pack on the solution.
Tracking issue + Remove todo

2017-02-24 22:13 UTC, pranavkm commented on build/targets/standard-lifecycle.targets
> +  <!-- TODO implement. See https://github.com/aspnet/BuildTools/issues/162 -->
Remove the target since it's not doing anything

2017-02-24 22:13 UTC, pranavkm commented on build/KoreBuild.ps1
> +exec dotnet build `@"$msBuildResponseFile"
Add a trailing new line to these files. There's a bunch missing these

2017-02-27 17:14 UTC, natemcmaster commented
Will do this later. Too many people still using 'dev' branch.

2017-03-01 17:48 UTC, natemcmaster commented
MVC merged sooner than expected. Now all Universe repos are on feature/msbuild. Let's move this to dev.

2017-03-01 17:51 UTC, natemcmaster commented on build/targets/standard-lifecycle.targets
> +    <!-- TODO consider using GeneratePackageOnBuild or calling Pack on the solution.
https://github.com/aspnet/KoreBuild/issues/184

2017-03-01 17:54 UTC, natemcmaster commented on build/KoreBuild.ps1
> -    InstallSharedRuntime '1.0.0' 'preview'
A few of our tools do, but the 1.0.0-rc4 SDK installs both the 1.0.4 and 1.1.1 runtimes automatically

2017-03-01 17:57 UTC, natemcmaster commented on build/dotnet/dotnet-install.ps1
>  .PARAMETER Verbose
These changes reflect updates and bug fixes to the dotnet-install.ps1 script in https://github.com/dotnet/cli. The layout of assets on dotnetcli.azureedge.net is slightly different for the MSBuild SDK than it was for project.json SDK.

2017-03-01 18:09 UTC, natemcmaster commented
🆙 :date: added changes per PR feedback

2017-03-01 22:51 UTC, natemcmaster commented
Before we merge this, I've tagged the current version of 'dev' as "legacy-build". I'm updating any other aspnet repos to use this so that merging this MSBuild work shouldn't break them.

This intentionally means that anyone using "legacy-build" won't receive updates as we're no longer updating our project.json scripts.

2017-03-02 00:27 UTC, analogrelay approved these changes
Looks good to me

2017-03-02 01:08 UTC, merged