Make MSBuild the default lifecycle
aspnet/KoreBuild pull request #180
Opened 2017-02-22 01:21 UTC by natemcmaster

Changes the default lifecycle from Sake to MSBuild. This will require updating the command-line syntax for anyone calling 'build.cmd'

Removes NPM, Grunt, and bower from the default lifecycle. Resolves #173 
Replaces the "update volatile feeds" step with a MSBuild target. See https://github.com/aspnet/BuildTools/pull/179

2017-02-22 15:43 UTC, pranavkm requested changes

2017-02-22 15:43 UTC, pranavkm commented on build/KoreBuild.ps1
> +$allparams        | Out-File -Encoding ASCII -FilePath $msBuildResponseFile -Append
Couldn't we move this in to the declaration of `$msBuildArguments`?

2017-02-22 15:43 UTC, pranavkm commented on build/KoreBuild.sh
> +echo -e "$msbuild_args" >> $msbuildResponseFile
Same thing - does moving it inline work?

2017-02-22 15:43 UTC, pranavkm commented on build/targets/KoreBuild.Common.targets
> +    <UpdateFeeds Include="AspNetCore" Value="$(NUGET_VOLATILE_FEED_AspNetCore)" Condition="'$(NUGET_VOLATILE_FEED_AspNetCore)' != ''" />
This is not the only feed we modify (although it's the one we most commonly change). Should be able to call `Environment.GetEnvironmentVariables` + StartsWith to filter

2017-02-22 15:43 UTC, pranavkm commented on build/targets/KoreBuild.DefaultLifecycle.targets
> +  <Target Name="Initialize" DependsOnTargets="RestoreSolutions" />
What of npm, grunt \ gulp?

2017-02-22 16:56 UTC, natemcmaster commented on build/targets/KoreBuild.DefaultLifecycle.targets
> +  <Target Name="Initialize" DependsOnTargets="RestoreSolutions" />
Intentionally removed. As far as I can tell, no one uses grunt, we never supported gulp, and SignalR is the only one that actually builds JavaScript...and it doesn't rely on KoreBuild to do that. The other usages of JS stuff are for samples.

cref #173

2017-02-22 17:00 UTC, natemcmaster commented on build/KoreBuild.sh
> +echo -e "$msbuild_args" >> $msbuildResponseFile
Inlining with the previous statement produced `\n` literals instead of newline characters :-/

2017-02-22 17:00 UTC, natemcmaster commented on build/KoreBuild.ps1
> +$allparams        | Out-File -Encoding ASCII -FilePath $msBuildResponseFile -Append
Yeah probably.

2017-02-22 17:14 UTC, natemcmaster commented on build/targets/KoreBuild.Common.targets
> +    <UpdateFeeds Include="AspNetCore" Value="$(NUGET_VOLATILE_FEED_AspNetCore)" Condition="'$(NUGET_VOLATILE_FEED_AspNetCore)' != ''" />
Which other feeds do we tweak? Can we just add an explicit list?

2017-02-24 18:41 UTC, natemcmaster commented on build/targets/KoreBuild.DefaultLifecycle.targets
> +'Restore' is defined in Microsoft.Common.targets
/cc @pranavkm . cref https://github.com/aspnet/KoreBuild/pull/181#issuecomment-282369303

2017-02-24 19:01 UTC, pranavkm commented on build/targets/KoreBuild.Common.targets
> +    <UpdateFeeds Include="AspNetCore" Value="$(NUGET_VOLATILE_FEED_AspNetCore)" Condition="'$(NUGET_VOLATILE_FEED_AspNetCore)' != ''" />
We add one for Universe `NUGET_VOLATILE_FEED_ARTIFACTS` (which is when it's trying to build against each other). We could just use an explicit list for now.

2017-02-24 19:08 UTC, natemcmaster commented on build/targets/KoreBuild.Common.targets
> +    <UpdateFeeds Include="AspNetCore" Value="$(NUGET_VOLATILE_FEED_AspNetCore)" Condition="'$(NUGET_VOLATILE_FEED_AspNetCore)' != ''" />
Thanks. I'd prefer that for simplicity. While possible to use GetEnvironmentVariables, the syntax to split a list of Key=Value pairs is hideous in MSBuild.

2017-02-28 18:44 UTC, natemcmaster commented
:up: :date:

2017-02-28 18:48 UTC, davidfowl commented
build.cmd still works right?

2017-02-28 19:36 UTC, natemcmaster commented
@davidfowl yes, it still works. But it will change the syntax of arguments passed to build.cmd. Instead of `build.cmd target1 target2`, it is now build.cmd + MSBuild args, or `build.cmd /t:Target1 /t:Target2` 

We'll need to make one tweak to build.ps1 to address #179 (changes `korebuild.ps1 $args` to `korebuild.ps1 @args`).

2017-03-01 18:37 UTC, natemcmaster commented
:bell:

2017-03-02 00:28 UTC, analogrelay approved these changes

2017-03-02 02:16 UTC, closed without merging

2017-03-02 02:17 UTC, natemcmaster commented
Merged https://github.com/aspnet/KoreBuild/commit/afa9dcacc2ae0609ad597084756fd28f7d87e469