Work around Microsoft/msbuild#1792
aspnet/KoreBuild pull request #192
Opened 2017-03-05 21:59 UTC by dougbu

- piping MsBuild output into `tee` cleans up the excess ANSI character codes

Extend the related `/clp:DisableConsoleColor` fix in fc6f034 to Windows CI machines.

2017-03-05 22:01 UTC, dougbu commented
Yes, this works. See aspnet/Mvc#5906 test PR and its Travis results: https://travis-ci.org/aspnet/Mvc/builds/207844301 and specifically a raw log e.g. https://s3.amazonaws.com/archive.travis-ci.org/jobs/207844302/log.txt

2017-03-05 22:02 UTC, dougbu commented
Would appreciate your thoughts too @natemcmaster

2017-03-06 16:48 UTC, natemcmaster commented
Does DisableConsoleColor workaround microsoft/msbuild#1792 on Windows? PowerShell also has `tee`.

2017-03-06 17:22 UTC, dougbu commented
@natemcmaster Microsoft/msbuild#1792 is specific to Travis. No need to use `tee` with AppVeyor or TeamCity.

2017-03-06 17:30 UTC, natemcmaster requested changes

2017-03-06 17:30 UTC, natemcmaster commented on build/KoreBuild.sh
> +        $cmd "$@" | tee /dev/null
Add `set -o pipefail` to the top of file. Otherwise this will cause all commands to exit with exit code 0.

2017-03-06 17:44 UTC, dougbu commented on build/KoreBuild.sh
> +        $cmd "$@" | tee /dev/null
:ok:

Strange that didn't happen in my local testing. For example I ran `./build.sh /t:fail` after `export TRAVIS=true` and the script noticed the non-`0` exit code.

2017-03-06 17:53 UTC, natemcmaster commented on build/KoreBuild.sh
> +        $cmd "$@" | tee /dev/null
```sh
#!/usr/bin/env sh

test -z "abc" | tee /dev/null
echo "Exited $?"

set -o pipefail

test -z "abc" | tee /dev/null
echo "Exited $?"
```

2017-03-06 18:02 UTC, dougbu commented on build/KoreBuild.sh
> +        $cmd "$@" | tee /dev/null
I said it was strange.

2017-03-06 18:02 UTC, dougbu commented
:up::date:

2017-03-06 18:04 UTC, natemcmaster approved these changes

2017-03-06 18:16 UTC, dougbu commented
0a4214d

2017-03-06 18:16 UTC, closed without merging