Disable xunit auto reporters when other test loggers are enabled
aspnet/KoreBuild pull request #230
Opened 2017-04-21 23:32 UTC by natemcmaster

Right now CI shows duplicate test results

1. From TRX logger.
2. From xunit's TeamCity auto-reporter.

This will disable the auto-reporter in favor of TRX reporter.

**FYI**: this won't take effect until we upgrade to xunit 2.3. cref https://github.com/xunit/visualstudio.xunit/pull/108

Cons:

- TC auto reporter reports tests as they happen but TRX only happens when the test process is done and the .trx file is produced
- For new build configs, test results don't light up in TC unless you add the XML report processing feature. https://confluence.jetbrains.com/display/TCD10/XML+Report+Processing. We already have this enabled on all of our test configs.

Pros:

- Reduced console output.
- In some cases (e.g. parallel test runs), the TC reporter does not properly report tests. See #198 
- TRX reporter shows output that TC auto reporter does not. Example:  ![image](https://cloud.githubusercontent.com/assets/2696087/25298952/29caed14-26af-11e7-9754-87a99469b1b2.png)

2017-04-21 23:52 UTC, dougbu commented
Thanks @natemcmaster. I'll look at this tonight.

There's an additional pro: TRX reporter reports some test failures that TC reporter completely ignores. (Our CI reports did _not_ double the number of tests when we re-enabled TRX reporting.)

2017-04-22 02:15 UTC, dougbu requested changes

2017-04-22 02:15 UTC, dougbu commented on build/targets/KoreBuild.SolutionBuild.targets
> +    <VSTestLogger Condition=" '$(VSTestLogger)' == '' AND '$(TEAMCITY_PROJECT_NAME)' != '' ">trx</VSTestLogger>
Revert the `TEAMCITY_VERSION` to `TEAMCITY_PROJECT_NAME` change.

2017-04-22 02:15 UTC, dougbu commented on build/targets/KoreBuild.SolutionBuild.targets
> +    <!-- ensure AppVeyor's auto test reporter remaines enabled -->
"remains"

2017-04-22 02:15 UTC, dougbu commented on build/targets/KoreBuild.SolutionBuild.targets
> +      <TestRunSettings Condition=" '$(VSTestLogger)' != '' AND '$(VSTestAutoReporters)' != 'true' ">RunConfiguration.NoAutoReporters=true</TestRunSettings>
Name this property `VSTestCLIRunSettings`.

2017-04-22 02:15 UTC, dougbu commented on build/targets/KoreBuild.SolutionBuild.targets
> +      <TestRunSettings Condition=" '$(VSTestLogger)' != '' AND '$(VSTestAutoReporters)' != 'true' ">RunConfiguration.NoAutoReporters=true</TestRunSettings>
This should also preserve any existing value e.g.
``` xml
<VSTestCLIRunSettings>$(VSTestCLIRunSettings);RunConfiguration.NoAutoReporters=true</TestRunSettings>
```

2017-04-22 02:15 UTC, dougbu commented on build/targets/KoreBuild.SolutionBuild.targets
> +      Properties="$(_SolutionProperties);VSTestLogger=$(VSTestLogger);VSTestNoBuild=$(VSTestNoBuild);VSTestCLIRunSettings=$(TestRunSettings)"
Need quotes around the `$(VSTestCLIRunSettings)` value if it can contain semicolons (as I suggested above).

2017-04-22 03:20 UTC, natemcmaster commented on build/targets/KoreBuild.SolutionBuild.targets
> +      Properties="$(_SolutionProperties);VSTestLogger=$(VSTestLogger);VSTestNoBuild=$(VSTestNoBuild);VSTestCLIRunSettings=$(TestRunSettings)"
Played with it a little. Quotes mess it up, but `.Replace(';','%3B')` should do the trick.

2017-04-22 03:21 UTC, natemcmaster commented
:up: :date:

2017-04-22 03:34 UTC, dougbu approved these changes
:shipit: from me. Agree @pranavkm should have a look too.

2017-04-22 03:34 UTC, dougbu commented on build/targets/KoreBuild.SolutionBuild.targets
> +    <VSTestAutoReporters Condition="'$(APPVEYOR_API_URL)' != ''">true</VSTestAutoReporters>
Does something set `$(VSTestLogger)` when on AppVeyor? If not, the `$(VSTestLogger)` condition may be enough -- no need for `$(VSTestAutoReporters)`.

2017-04-24 16:50 UTC, natemcmaster commented on build/targets/KoreBuild.SolutionBuild.targets
> +    <VSTestAutoReporters Condition="'$(APPVEYOR_API_URL)' != ''">true</VSTestAutoReporters>
I added this as an escape hatch in case we want to force the TeamCity auto-reporter to turn on without needing to make changes KoreBuild.

2017-04-24 17:06 UTC, dougbu commented on build/targets/KoreBuild.SolutionBuild.targets
> +    <VSTestAutoReporters Condition="'$(APPVEYOR_API_URL)' != ''">true</VSTestAutoReporters>
Then support `$(VSTestAutoReporters)` but get rid of the unnecessary special case for `'$(APPVEYOR_API_URL)' != ''` e.g.
``` xml
<VSTestAutoReporters Condition=" '$(VSTestAutoReporters)' == '' AND Condition=" '$(VSTestLogger)' != '' ">false</VSTestAutoReporters>
<VSTestAutoReporters Condition=" '$(VSTestAutoReporters)' == '' >true</VSTestAutoReporters>
```

2017-04-24 21:54 UTC, natemcmaster commented on build/targets/KoreBuild.SolutionBuild.targets
> +    <VSTestAutoReporters Condition="'$(APPVEYOR_API_URL)' != ''">true</VSTestAutoReporters>
sounds good

2017-04-24 23:51 UTC, merged